config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "owner" => "pages#owner"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def owner
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "新時代の部屋探し", root_path, class: "navbar-brand" %>
      
        <a class="navbar-brand" href="#">MFA</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About Us", root_path %></li>
          <li><%= link_to "MFAとは", about_path %></li>
          <li><%= link_to "使い方", about_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </div><!-- /.container -->
</nav>

app/views/layouts/_owner_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "MFA", root_path, class: "navbar-brand" %>
      
        <a class="navbar-brand">新時代の部屋探し</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About Us", about_path %></li>
          <li><%= link_to "MFAとは", about_path %></li>
          <li><%= link_to "使い方", about_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Account settings", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MFA</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>


    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
		  <%= yield %>
		
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>

app/views/pages/home.html.erb
<%= render 'layouts/header' %>

<section class="container">
    <div class="main-title">
      <div class="clearfix main-inner">
        <h2>
          SmartでCheapな<br>新時代の部屋探し    
        </h2>
        <div class="video">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/Qd-GkbCFeok?ecver=1" frameborder="0" allowfullscreen></iframe>
        </div><!-- video -->
       <!--  <div class="app-icons">
          <img src="app/assets/images/App-store.png" alt="App-store">
          <img src="images/android-download.png" alt="App-store">
        </div><!-- app-icons -->
        
        <% if user_signed_in? %>
          #do something
        <% else %>
          <div class="button">
            <span>
              <%= link_to "Sign up", new_user_registration_path %>
            </span>
          </div><!-- button -->  
          <p>会員の方はこちらから<%= link_to "ログイン", new_user_session_path %></p>
        <% end %>

        <div class="owner-register">
          <p>家主はこちらから<%= link_to "家主ページ", owner_path %></p>
        </div><!-- owner-register -->
      </div><!-- main-inner -->
    </div><!-- main-title -->
  </section>

  <section>
    <div class="reason-block">
      <h2>3つの特徴</h2>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <p>全物件仲介手数料無料</p>
          <ul>
            <i class="icon-checkmark"></i>
            <li>無店舗・IT効率化によるコストカット</li>
            <li>家主と借手の直接やりとり</li>
         </ul>
        </div>

        <div class="col-md-4">
          <p>実際の住人によるレビュー</p>
          <ul>
            <i class="icon-checkmark"></i>
            <li>実際の利用者の生の声が聞ける</li>
            <li>利用前から部屋のメリット・デメリットがわかる</li>
           </ul>
        </div>

        <div class="col-md-4">
          <p>お部屋の持ち込み</p>
          <ul>
            <i class="icon-checkmark"></i>
            <li>URLを送って返事を待つだけ</li>
            <li>おとり物件のチェックにも</li>
          </ul>
        </div>
      </div><!-- row -->
    </div><!-- container -->
  </section>
</section>

</body>
</html>

app/views/pages/owner.html.erb
<%= render 'layouts/owner_header' %>

<section class="container">
	<div class="main-title">
		<div class="clearfix main-inner">
			<h1>owner page</h1>
			<div class="button">
				<span>
				  <%= link_to "Sign up", new_user_registration_path %>
				</span>
			</div><!-- button -->  
			<div class="button">
				<span>
					<%= link_to "ログイン", new_user_session_path %>
				<span>
			</div><!-- button -->  
		</div><!-- main-inner -->
	</div><!-- main-title -->
</section>